/*******************************************************************************
* Copyright (C) 2019-2024 Maxim Integrated Products, Inc., All rights Reserved.
*
* This software is protected by copyright laws of the United States and
* of foreign countries. This material may also be protected by patent laws
* and technology transfer regulations of the United States and of foreign
* countries. This software is furnished under a license agreement and/or a
* nondisclosure agreement and may only be used or reproduced in accordance
* with the terms of those agreements. Dissemination of this information to
* any party or parties not specified in the license agreement and/or
* nondisclosure agreement is expressly prohibited.
*
* The above copyright notice and this permission notice shall be included
* in all copies or substantial portions of the Software.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
* OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
* MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
* IN NO EVENT SHALL MAXIM INTEGRATED BE LIABLE FOR ANY CLAIM, DAMAGES
* OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
* OTHER DEALINGS IN THE SOFTWARE.
*
* Except as contained in this notice, the name of Maxim Integrated
* Products, Inc. shall not be used except as stated in the Maxim Integrated
* Products, Inc. Branding Policy.
*
* The mere transfer of this software does not imply any licenses
* of trade secrets, proprietary technology, copyrights, patents,
* trademarks, maskwork rights, or any other form of intellectual
* property whatsoever. Maxim Integrated Products, Inc. retains all
* ownership rights.
*******************************************************************************/

// mms-anomaly-v2
// This file was @generated by ai8xize.py --verbose --test-dir demos --prefix mms-anomaly-v2 --checkpoint-file trained/mms-qat-v2-q.pth.tar --config-file networks/mms-anomaly-ai85.yaml --device MAX78000 --compact-data --timer 0 --display-checkpoint

#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include <stdio.h>
#include "mxc.h"
#include "dma.h"
#include "pb.h"
#include "camera.h"
#include "cnn.h"
#include "sampledata.h"
#include "sampleoutput.h"

volatile uint32_t cnn_time; // Stopwatch

void fail(void)
{
  printf("\n*** FAIL ***\n\n");
  while (1);
}

#define IMAGE_SIZE_X 128
#define IMAGE_SIZE_Y 128
#define CAMERA_SIZE_X 128
#define CAMERA_SIZE_Y 128
#define CAMERA_FREQ (10 * 1000 * 1000)
#define INPUT_WORDS_PER_CHANNEL ((IMAGE_SIZE_X * IMAGE_SIZE_Y) / 4)

// USER EDIT: Camera-backed CHW input buffers, one signed 8-bit channel per byte.
static uint32_t input_0_camera[INPUT_WORDS_PER_CHANNEL];
static uint32_t input_16_camera[INPUT_WORDS_PER_CHANNEL];
static uint32_t input_32_camera[INPUT_WORDS_PER_CHANNEL];

// Generated known-answer-test sample. Kept separate from the live camera input path.
static const uint32_t input_0[] = SAMPLE_INPUT_0;
static const uint32_t input_16[] = SAMPLE_INPUT_16;
static const uint32_t input_32[] = SAMPLE_INPUT_32;

void load_input(void)
{
  memcpy32((uint32_t *) 0x50400000, input_0_camera, INPUT_WORDS_PER_CHANNEL);
  memcpy32((uint32_t *) 0x50800000, input_16_camera, INPUT_WORDS_PER_CHANNEL);
  memcpy32((uint32_t *) 0x50c00000, input_32_camera, INPUT_WORDS_PER_CHANNEL);
}

static void load_sample_input(void)
{
  memcpy32(input_0_camera, input_0, INPUT_WORDS_PER_CHANNEL);
  memcpy32(input_16_camera, input_16, INPUT_WORDS_PER_CHANNEL);
  memcpy32(input_32_camera, input_32, INPUT_WORDS_PER_CHANNEL);

  memcpy32((uint32_t *) 0x50400000, input_0, INPUT_WORDS_PER_CHANNEL);
  memcpy32((uint32_t *) 0x50800000, input_16, INPUT_WORDS_PER_CHANNEL);
  memcpy32((uint32_t *) 0x50c00000, input_32, INPUT_WORDS_PER_CHANNEL);
}

static const uint32_t sample_output[] = SAMPLE_OUTPUT;
static int check_output(void)
{
  int i;
  uint32_t mask, len;
  volatile uint32_t *addr;
  const uint32_t *ptr = sample_output;

  while ((addr = (volatile uint32_t *) *ptr++) != 0) {
    mask = *ptr++;
    len = *ptr++;
    for (i = 0; i < len; i++)
      if ((*addr++ & mask) != *ptr++) {
        printf("Data mismatch (%d/%d) at address 0x%08x: Expected 0x%08x, read 0x%08x.\n",
               i + 1, len, addr - 1, *(ptr - 1), *(addr - 1) & mask);
        return CNN_FAIL;
      }
  }

  return CNN_OK;
}

static int32_t ml_data[CNN_NUM_OUTPUTS];

#define MMS_GRID_W 32
#define MMS_GRID_H 32
#define MMS_NUM_CELLS (MMS_GRID_W * MMS_GRID_H)
#define MMS_IMAGE_THRESHOLD_Q1000 250
#define MMS_PRINT_ANOMALY_MAP 1
#define MMS_PRINT_PGM_IMAGES 1
#define MMS_TRUE_LABEL "UNKNOWN"

static const char *mms_frame_source = "UNKNOWN";

static int clamp_u8(int v)
{
  if (v < 0)
    return 0;
  if (v > 255)
    return 255;
  return v;
}

static int sample_byte(const uint32_t *data, int index)
{
  return (int8_t) ((data[index >> 2] >> (8 * (index & 3))) & 0xff);
}

static uint8_t unsigned_to_signed(uint8_t val)
{
  return (uint8_t) ((int) val - 128);
}

static void process_stream_line(const uint8_t *line, uint32_t camera_y, uint32_t camera_w)
{
  uint8_t *r = (uint8_t *) input_0_camera;
  uint8_t *g = (uint8_t *) input_16_camera;
  uint8_t *b = (uint8_t *) input_32_camera;
  uint32_t dst_y = camera_y * IMAGE_SIZE_Y / CAMERA_SIZE_Y;

  if (dst_y >= IMAGE_SIZE_Y)
    return;

  for (uint32_t x = 0; x < IMAGE_SIZE_X; x++) {
    uint32_t src_x = x * camera_w / IMAGE_SIZE_X;
    const uint8_t *src = line + 4 * src_x;
    uint32_t dst_i = dst_y * IMAGE_SIZE_X + x;

    r[dst_i] = unsigned_to_signed(src[0]);
    g[dst_i] = unsigned_to_signed(src[1]);
    b[dst_i] = unsigned_to_signed(src[2]);
  }
}

static void capture_camera_stream_to_input(void)
{
  uint8_t *data;
  int buffer_size = camera_get_stream_buffer_size();
  uint32_t line_bytes = CAMERA_SIZE_X * 4;
  uint32_t lines_per_buffer = (uint32_t) buffer_size / line_bytes;
  uint32_t camera_y = 0;

  if (lines_per_buffer == 0)
    lines_per_buffer = 1;

  memset(input_0_camera, 0, sizeof(input_0_camera));
  memset(input_16_camera, 0, sizeof(input_16_camera));
  memset(input_32_camera, 0, sizeof(input_32_camera));

  camera_start_capture_image();

  while (!camera_is_image_rcv()) {
    data = get_camera_stream_buffer();
    if (data != NULL) {
      for (uint32_t line = 0; line < lines_per_buffer && camera_y < CAMERA_SIZE_Y; line++) {
        process_stream_line(data + line * line_bytes, camera_y, CAMERA_SIZE_X);
        camera_y++;
      }
      release_camera_stream_buffer();
    }
  }

  while ((data = get_camera_stream_buffer()) != NULL) {
    for (uint32_t line = 0; line < lines_per_buffer && camera_y < CAMERA_SIZE_Y; line++) {
      process_stream_line(data + line * line_bytes, camera_y, CAMERA_SIZE_X);
      camera_y++;
    }
    release_camera_stream_buffer();
  }

  printf("Camera stream lines copied: %lu/%d\n", (unsigned long) camera_y, CAMERA_SIZE_Y);
  stream_stat_t *stat = get_camera_stream_statistic();
  printf("Camera DMA transfers: %lu, overflow: %lu\n",
         (unsigned long) stat->dma_transfer_count, (unsigned long) stat->overflow_count);
}

static void print_input_ppm(void)
{
  printf("BEGIN_INPUT_PPM\n");
  printf("P3\n");
  printf("128 128\n");
  printf("255\n");

  for (int y = 0; y < 128; y++) {
    for (int x = 0; x < 128; x++) {
      int i = y * 128 + x;
      int r = sample_byte(input_0_camera, i) + 128;
      int g = sample_byte(input_16_camera, i) + 128;
      int b = sample_byte(input_32_camera, i) + 128;

      printf("%d %d %d%c", clamp_u8(r), clamp_u8(g), clamp_u8(b), x == 127 ? '\n' : ' ');
    }
  }

  printf("END_INPUT_PPM\n");
}

static int anomaly_probability_u8(const uint16_t *out16, int i)
{
  int normal = (int8_t) ((out16[i] >> 1) & 0xff);
  int anomaly = (int8_t) ((out16[i + MMS_NUM_CELLS] >> 1) & 0xff);
  int margin = anomaly - normal;
  int32_t y_q16 = margin * 256; // y = margin / 256 = (anomaly - normal) / (2 * 128)
  int64_t y2_q16 = ((int64_t) y_q16 * y_q16) >> 16;
  int64_t numerator_q16 = ((int64_t) y_q16 * ((27LL << 16) + y2_q16)) >> 16;
  int64_t denominator_q16 = (27LL << 16) + 9 * y2_q16;
  int32_t tanh_q15 = (int32_t) ((numerator_q16 * 32768) / denominator_q16);

  // sigmoid(x) = (1 + tanh(x / 2)) / 2, mapped to an 8-bit probability.
  return clamp_u8(128 + (tanh_q15 * 127) / 32768);
}

static void print_anomaly_pgm(const int32_t *output)
{
  const uint16_t *out16 = (const uint16_t *) output;

  printf("BEGIN_ANOMALY_PGM\n");
  printf("P2\n");
  printf("%d %d\n", MMS_GRID_W, MMS_GRID_H);
  printf("255\n");

  for (int y = 0; y < MMS_GRID_H; y++) {
    for (int x = 0; x < MMS_GRID_W; x++) {
      int i = y * MMS_GRID_W + x;

      printf("%d%c", anomaly_probability_u8(out16, i), x == MMS_GRID_W - 1 ? '\n' : ' ');
    }
  }

  printf("END_ANOMALY_PGM\n");
}

// USER EDIT: Decode the 2x32x32 anomaly logits and print an image-level result.
static void print_mms_prediction(const int32_t *output)
{
  const uint16_t *out16 = (const uint16_t *) output;
  int anomalous_cells = 0;
  int max_margin = -32768;
  int32_t margin_sum = 0;
  int32_t probability_sum = 0;
  int image_score_q1000;

  for (int i = 0; i < MMS_NUM_CELLS; i++) {
    int normal = (int8_t) ((out16[i] >> 1) & 0xff);
    int anomaly = (int8_t) ((out16[i + MMS_NUM_CELLS] >> 1) & 0xff);
    int margin = anomaly - normal;
    int probability = anomaly_probability_u8(out16, i);

    if (probability >= 128)
      anomalous_cells++;
    if (margin > max_margin)
      max_margin = margin;
    margin_sum += margin;
    probability_sum += probability;
  }

  image_score_q1000 = (probability_sum * 1000 + 255 * MMS_NUM_CELLS / 2) /
                      (255 * MMS_NUM_CELLS);

  printf("MMS anomaly result:\n");
  printf("  Guess: %s\n",
         image_score_q1000 >= MMS_IMAGE_THRESHOLD_Q1000 ? "DAMAGED" : "GOOD");
  printf("  Image anomaly score: %d.%03d, threshold: %d.%03d\n",
         image_score_q1000 / 1000, image_score_q1000 % 1000,
         MMS_IMAGE_THRESHOLD_Q1000 / 1000, MMS_IMAGE_THRESHOLD_Q1000 % 1000);
  printf("  Anomalous cells: %d/%d\n", anomalous_cells, MMS_NUM_CELLS);
  printf("  Max anomaly margin: %d\n", max_margin);
  printf("  Mean anomaly margin: %ld\n", (long) (margin_sum / MMS_NUM_CELLS));

#if MMS_PRINT_ANOMALY_MAP
  printf("\nAnomaly map (32x32):\n");
  for (int y = 0; y < MMS_GRID_H; y++) {
    for (int x = 0; x < MMS_GRID_W; x++) {
      int i = y * MMS_GRID_W + x;
      int probability = anomaly_probability_u8(out16, i);
      char c = '.';

      if (probability >= 224)
        c = '#';
      else if (probability >= 192)
        c = '*';
      else if (probability >= 128)
        c = '+';

      putchar(c);
    }
    putchar('\n');
  }
  putchar('\n');
#endif

#if MMS_PRINT_PGM_IMAGES
  printf("BEGIN_MMS_FRAME\n");
  printf("BEGIN_MMS_INFO\n");
  printf("source=%s\n", mms_frame_source);
  printf("guess=%s\n",
         image_score_q1000 >= MMS_IMAGE_THRESHOLD_Q1000 ? "DAMAGED" : "GOOD");
  printf("true=%s\n", MMS_TRUE_LABEL);
  printf("image_score_q1000=%d\n", image_score_q1000);
  printf("threshold_q1000=%d\n", MMS_IMAGE_THRESHOLD_Q1000);
  printf("anomalous_cells=%d\n", anomalous_cells);
  printf("num_cells=%d\n", MMS_NUM_CELLS);
  printf("max_margin=%d\n", max_margin);
  printf("mean_margin=%ld\n", (long) (margin_sum / MMS_NUM_CELLS));
  printf("END_MMS_INFO\n");
  print_input_ppm();
  print_anomaly_pgm(output);
  printf("END_MMS_FRAME\n");
#endif
}

static void run_cnn_once(void (*input_loader)(void))
{
  cnn_time = 0;
  cnn_init(); // Bring state machine into consistent state
  cnn_load_weights(); // Load kernels
  cnn_load_bias();
  cnn_configure(); // Configure state machine
  input_loader();
  cnn_start(); // Start CNN processing

  while (cnn_time == 0)
    MXC_LP_EnterSleepMode(); // Wait for CNN
}

int main(void)
{
  int dma_channel;
  int ret;

#if defined(BOARD_FTHR_REVA)
  MXC_Delay(200000);
  Camera_Power(POWER_ON);
#endif

  MXC_ICC_Enable(MXC_ICC0); // Enable cache

  // Switch to 100 MHz clock
  MXC_SYS_Clock_Select(MXC_SYS_CLOCK_IPO);
  SystemCoreClockUpdate();

  printf("Waiting...\n");

  // DO NOT DELETE THIS LINE:
  MXC_Delay(SEC(2)); // Let debugger interrupt if needed

  MXC_DMA_Init();
  dma_channel = MXC_DMA_AcquireChannel();

  printf("Init Camera.\n");
  camera_init(CAMERA_FREQ);
  ret = camera_setup(CAMERA_SIZE_X, CAMERA_SIZE_Y, PIXFORMAT_RGB888, FIFO_THREE_BYTE, STREAMING_DMA,
                     dma_channel);
  if (ret != STATUS_OK) {
    printf("Error returned from setting up camera. Error %d\n", ret);
    return -1;
  }

  // Enable peripheral, enable CNN interrupt, turn on CNN clock
  // CNN clock: APB (50 MHz) div 1
  cnn_enable(MXC_S_GCR_PCLKDIV_CNNCLKSEL_PCLK, MXC_S_GCR_PCLKDIV_CNNCLKDIV_DIV1);

  printf("\n*** CNN Inference Test mms-anomaly-v2 ***\n");

  printf("Running startup KAT with generated sample input.\n");
  mms_frame_source = "KAT_SAMPLE";
  run_cnn_once(load_sample_input);
  if (check_output() != CNN_OK)
    fail();
  cnn_unload((uint32_t *) ml_data);
  printf("\n*** STARTUP KAT PASS ***\n\n");
  printf("Startup KAT decoded output:\n");
  print_mms_prediction(ml_data);

  while (1) {
    printf("\nPress PB1(SW1) to capture an image.\n");
    while (!PB_Get(0)) {}
    while (PB_Get(0)) {}

    printf("Stream camera frame to CNN input buffers.\n");
    capture_camera_stream_to_input();

    mms_frame_source = "LIVE_CAMERA";
    run_cnn_once(load_input);
    cnn_unload((uint32_t *) ml_data);

    printf("\n*** CNN DONE ***\n\n");
    print_mms_prediction(ml_data);

#ifdef CNN_INFERENCE_TIMER
    printf("Approximate inference time: %u us\n\n", cnn_time);
#endif
  }

  return 0;
}

/*
  SUMMARY OF OPS
  Hardware: 186,941,440 ops (186,122,240 macc; 819,200 comp; 0 add; 0 mul; 0 bitwise)
    Layer 0: 966,656 ops (884,736 macc; 81,920 comp; 0 add; 0 mul; 0 bitwise)
    Layer 1: 1,228,800 ops (1,179,648 macc; 49,152 comp; 0 add; 0 mul; 0 bitwise)
    Layer 2: 3,563,520 ops (3,538,944 macc; 24,576 comp; 0 add; 0 mul; 0 bitwise)
    Layer 3: 5,332,992 ops (5,308,416 macc; 24,576 comp; 0 add; 0 mul; 0 bitwise)
    Layer 4: 7,110,656 ops (7,077,888 macc; 32,768 comp; 0 add; 0 mul; 0 bitwise)
    Layer 5: 9,469,952 ops (9,437,184 macc; 32,768 comp; 0 add; 0 mul; 0 bitwise)
    Layer 6: 9,469,952 ops (9,437,184 macc; 32,768 comp; 0 add; 0 mul; 0 bitwise)
    Layer 7: 9,469,952 ops (9,437,184 macc; 32,768 comp; 0 add; 0 mul; 0 bitwise)
    Layer 8: 9,469,952 ops (9,437,184 macc; 32,768 comp; 0 add; 0 mul; 0 bitwise)
    Layer 9: 9,469,952 ops (9,437,184 macc; 32,768 comp; 0 add; 0 mul; 0 bitwise)
    Layer 10: 9,469,952 ops (9,437,184 macc; 32,768 comp; 0 add; 0 mul; 0 bitwise)
    Layer 11: 9,469,952 ops (9,437,184 macc; 32,768 comp; 0 add; 0 mul; 0 bitwise)
    Layer 12: 9,469,952 ops (9,437,184 macc; 32,768 comp; 0 add; 0 mul; 0 bitwise)
    Layer 13: 9,469,952 ops (9,437,184 macc; 32,768 comp; 0 add; 0 mul; 0 bitwise)
    Layer 14: 9,469,952 ops (9,437,184 macc; 32,768 comp; 0 add; 0 mul; 0 bitwise)
    Layer 15: 9,469,952 ops (9,437,184 macc; 32,768 comp; 0 add; 0 mul; 0 bitwise)
    Layer 16: 9,469,952 ops (9,437,184 macc; 32,768 comp; 0 add; 0 mul; 0 bitwise)
    Layer 17: 9,469,952 ops (9,437,184 macc; 32,768 comp; 0 add; 0 mul; 0 bitwise)
    Layer 18: 9,469,952 ops (9,437,184 macc; 32,768 comp; 0 add; 0 mul; 0 bitwise)
    Layer 19: 9,469,952 ops (9,437,184 macc; 32,768 comp; 0 add; 0 mul; 0 bitwise)
    Layer 20: 7,102,464 ops (7,077,888 macc; 24,576 comp; 0 add; 0 mul; 0 bitwise)
    Layer 21: 5,332,992 ops (5,308,416 macc; 24,576 comp; 0 add; 0 mul; 0 bitwise)
    Layer 22: 5,332,992 ops (5,308,416 macc; 24,576 comp; 0 add; 0 mul; 0 bitwise)
    Layer 23: 5,332,992 ops (5,308,416 macc; 24,576 comp; 0 add; 0 mul; 0 bitwise)
    Layer 24: 3,555,328 ops (3,538,944 macc; 16,384 comp; 0 add; 0 mul; 0 bitwise)
    Layer 25: 32,768 ops (32,768 macc; 0 comp; 0 add; 0 mul; 0 bitwise)

  RESOURCE USAGE
  Weight memory: 181,112 bytes out of 442,368 bytes total (40.9%)
  Bias memory:   698 bytes out of 2,048 bytes total (34.1%)
*/
